import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import AppButton from '../components/Button/AppButton'
import styles from '../styles/Home.module.scss'

import { TodoContext } from '../context';

export default function Home() {

  const { theme } = React.useContext(TodoContext);
  console.log(theme);
  return (
    <div className={`${styles.container}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${theme ? 'light' : 'dark'}`}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <AppButton />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
